- number: "01"
  type: Web Developement
  description: "I build websites, mainly custom WordPress themes if you wish to edit and publish content yourself or Jekyll themes if you have static content.
  My focus is on Front-End, HTML5, CSS3, Sass and Javasript. But I also don't faint using PHP or Ruby."

- number: "02"
  type: Web Design
  description: "If you don't have a design for the site yet I can create your Web Presence.
  We think together about the best possible structure for the site, choose the colors and fonts and based on that I'll design a possible Website for you.
  Or two. Or three.."

- number: "03"
  type: Branding
  description: "If this is the first public presence or
  if you're not happy with your current branding I can help you creating a branding for your public presence."

- number: "04"
  type: Print Design
  description: "Not really my main profession however if you have a gig you'd like to promote,
  a flea market you want to advertise for, anything printed basically I can do the design for you."
