- number: "01"
  type: Web Developement
  description: I build responsive websites which are fast, robust and are easily maintainable. For that I create custom WordPress themes or a static Jekyll site if you have a website which doesn't need a lot of content updates.
  tools: I'm happy to work with the following tools and languages. HTML5, CSS3 / Sass, Javascript, Grunt, Bower, jQuery, Vue.js, PHP, Ruby, MySQL, Git and Github.


- number: "02"
  type: Web Design
  description: "I like to create clean aesthetically pleasing designs which drive users to take action. There are different ways to do so: I create Web Designs from scratch or use style guides to adapt it into a Web Design."
  tools: To create my designs I use Sketch, Adobe Software and Codepen.


- number: "03"
  type: Print Design
  description: Although digital design is where I spend the majority of my time in, I also have experience with branding and print design. My offers  range from a new logo, to a flyer to promote a local Flea Market or a printed booklet for your organisations annual report.
