- type: Web Developement
  description: I build websites. My strength is in Frontend, so HTML5, CSS3, Sass and Javasript. But I also don't faint using PHP code or Ruby. If you'd like a website you can maintain yourself on a regular basis I can create a custom WordPress Theme for you. I code it you maintain it. If you just wish a website which doesn't need much of updating I can create a Jekyll site for you.

- type: Web Design
  description: If you don't have a design for the site yet I can also create your Web Presence. We think together about the best possible structure for the site, choose the colors and fonts and based on that I create a possible Web Design for you. Or two. Or three..

- type: Branding
  description: If this is the first public presence or if you're not happy with your current branding we can think together about colors and fonts. I can also create a logo for you.

- type: Print Design
  description: Not really my main profession however if you have a gig you'd like to promote, a flea market you want to advertise for, anything printed basically I can to the design for you.
