- type: Web Developement
  description: I code. Preferably Front-End, so HTML5, CSS3, Sass and Javasript. But I also don't faint using PHP code or Ruby. So yes I can build your custom WordPress Theme, I can also create a Jekyll site for you if you don't wan't to change your content on a regular basis.

- type: Web Design
  description: Before I start coding I create Web Designs. You tell me what you want to tell with your website. Together we think about the best possible structure. Then you tell me your favourites colors, or the ones you really don't like, we speak about fonts and then I create a possible Web Design for you. Or two. (Or three..)

- type: Branding
  description: If this is the first presence or if you're not happy with your current branding we think together about colors, fonts, logos.

- type: Print Design
  description: Not really my main profession however if you have a gig you'd like to promote with a nice flyer, a fleemarket you want to advertise I can create a flyer for you. I also do photo books. 
