- type: Web Developement
  text: I work as a freelancer and I'm always happy to discuss new projects, so please get in touch if you have something in mind I could help you with!

- type: Web Design
  text: I work as a freelancer and I'm always happy to discuss new projects, so please get in touch if you have something in mind I could help you with!

- type: Branding
  text: I work as a freelancer and I'm always happy to discuss new projects, so please get in touch if you have something in mind I could help you with!

- type: Print Design
  text: I work as a freelancer and I'm always happy to discuss new projects, so please get in touch if you have something in mind I could help you with!
